### ISSUE TITLE
Some enchantments.

### ISSUE THREAD

**Issue by ianlavr** [ryyanmapes/minecart-mod#10]
**Locomotives:**
A more advanced and faster version of Minecart With Furnace which optionally can support FE.
**High Speed Redstone Rails:**
Faster Redstone Rails.
**Minecart With Fluid Tank:**
A moveable fluid storage. 10B/100B/1000B capacity.
**Soulfire Campfire Minecart:**
Nether variant of Campfire Minecart. Optionally can work faster in Nether.
**Energy Minecart (if you add FE support):**
Moveable FE storage. Capacity: 1000000FE Transfer rate: 100-500FE/t.
**Functional Minecarts:**
Crafting, brewing, sleeping etc
**Stopper Rails:**
Will stop minecarts. If powered with redstone signal will release them with a bit of momentum.
**Loaders:**
Will load minecarts with items, liquids(if you add liquids support) and energy(if you add FE support).
**Unloaders:**
Opposite of Loaders.

_Maybe a guide book using Patchouli?_
_More efficient way of crafting rails?_
_Maybe minecarts with more item capacity?_

**Comment by ryyanmapes** [comment]
The soulfire minecart and high speed rails already exist. I may look into the energy and fluid carts down the road, but not soon. Functional minecarts are a good idea, but seem boring to add. I'm planning on adding stopper rails and loaders/unloaders in the next update.

**Comment by ianlavr** [comment]
ok good

**Comment by ryyanmapes** [comment]
Locking rails, loaders and unloaders, and fluid and energy carts have all been added.
