### ISSUE TITLE
more specialized rails

### ISSUE THREAD

**Issue by Gitcrafter** [ryyanmapes/minecart-mod#13]
Hello, can you add crossings and Y-switches(switches that can´t go straight and instead switch between going to the right/left)?

**Comment by ryyanmapes** [comment]
Y-switches are included in vanilla, by powering a rail at a T junction. Rail crossings are being added for the next update.

**Comment by Gitcrafter** [comment]
Oh, I didn´t knew that, looking forward to the crossings
