### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by foxanthony1** [ryyanmapes/minecart-mod#14]
Config options would be great. I definitely don't want chunk loading - that can cause problems on servers I would like to avoid. I also like to avoid world gen if at all possible.

 I really only want the unloader because the old vanilla circuit for that is broken and your mod makes it work. I'm not sure what the benefit is to the loader especially since it's not any faster than a vanilla hopper.

Faster unloading would be great. I have Engineer's Decor hoppers and they do 32 items at a time but that's useless with this. 

It would be nice if the unloader/loaders had both input and output hoppers built in.

What would be great is if you made another mod, "Minecart Loader/Unloader" that works the way I've described here. The title itself I think would attract a lot of people. I'm not saying get rid of this mod just make another simpler one. 

Oh yeah. The steel thing seems kind of odd with mods that add steel. Maybe you could make the recipes straight vanilla?

**Comment by ryyanmapes** [comment]
The next update will have a config option to modify the chunk loader fuel multiplier. Setting that to zero will effectively disable the chunk loader. I will look into a buff for the loader and unloader speeds.

**Comment by foxanthony1** [comment]
How about the loader/unloader powering the rail when it's done it's job. No point in using the loader, as far as I can tell, when vanilla does the same thing cheaper.

**Comment by ryyanmapes** [comment]
You can do that currently with the help of a comparator, but in the next update we're going to add an option to just power the block.

**Comment by foxanthony1** [comment]
So people won't need redstone to use it?

That's the main thing I'm trying to get away from. I know how to do it, but most modded players don't want to mess with redstone.

Your solution for the chunk loader will have players making it and finding out it doesn't work. I removed the recipe for it with Crafttweaker so that won't happen.

**Comment by foxanthony1** [comment]
How about this: A powered rail that detects if a minecart chest is empty or full.

It has a normal and an inverted mode.

In normal mode it powers when the minecart chest is full and in inverted mode it powers when the chest is empty.

**Comment by ryyanmapes** [comment]
This is already a setting selectable on the loader and unloader.
