### ISSUE TITLE
my game crashes when activating the chunk loader cart

### ISSUE THREAD

**Issue by daympegi1539** [ryyanmapes/minecart-mod#17]
When I put in the nether stars and press the power button, or run it over an activator rail, the game crashes. 

this is my crash log, I greatly appreciate any help to resolve the issue.
[crash-2021-06-23_00.24.16-server.txt](https://github.com/ryyanmapes/minecart-mod/files/6698898/crash-2021-06-23_00.24.16-server.txt)

**Comment by ryyanmapes** [comment]
Huh, guess I never tested the chunk loader cart in other dimensions. I'm going to look into this.

**Comment by ryyanmapes** [comment]
Ok, I think this due to Immersive Portals. Try downloading a 1.16.5 version of that mod, and report back if you still have issues.

**Comment by daympegi1539** [comment]
Thank you for helping! For some reason, immersive portals 1.16.5 would crash unlike 1.16.4, so I just left out any immersive portals, also deleting the config as well if it made a difference. I also tried in a new world and it still ended up crashing once starting.

This is my crash report after following the advice
[crash-2021-06-23_14.54.01-server.txt](https://github.com/ryyanmapes/minecart-mod/files/6704251/crash-2021-06-23_14.54.01-server.txt)

I also took out every mod except this and optifine and still got a crash on a new world, this is the crash report for that attempt.
[crash-2021-06-23_15.00.16-server.txt](https://github.com/ryyanmapes/minecart-mod/files/6704274/crash-2021-06-23_15.00.16-server.txt)

Hopefully any of this info may help, I greatly appreciate your help.

**Comment by ryyanmapes** [comment]
Huh, that's weird. Do chunk loader blocks still work okay?

**Comment by daympegi1539** [comment]
Ok so I tested the chunk loader block itself and still got a crash report, so I'm guessing it's the loader itself

this is the report
[crash-2021-06-26_20.54.04-server.txt](https://github.com/ryyanmapes/minecart-mod/files/6720865/crash-2021-06-26_20.54.04-server.txt)

**Comment by ryyanmapes** [comment]
I can't reproduce this on my side. From your crash logs, it seems like the error is occurring because Forge's code can't find it's own method (which I am initially calling to keep chunks loaded). Maybe try re-installing Forge? It may be an issue particular to your current version of forge. Other than that, I have no idea. Sorry I can't be of more help!
