### ISSUE TITLE
wooden rails do not break in water like other rails

### ISSUE THREAD

**Issue by Wedge1453** [ryyanmapes/minecart-mod#19]
![2021-07-18_23 26 50](https://user-images.githubusercontent.com/76813383/126357806-761eddaf-d978-4ffb-a116-7400d2a12c39.png)

**Comment by ryyanmapes** [comment]
I'm going to look into this.

**Comment by KaziiTheAvali** [comment]
in reality i think this would be fine expecally if this mod will be updated to 1.17 since rails do not break in water in that verson

**Comment by ryyanmapes** [comment]
Fixed in new version. Thanks for reporting this, forgot to test this somehow.
