### ISSUE TITLE
[1.16.5 - 1.3.8] Breaking Minecart with Tank entity drops empty Minecart and Chunk Loader

### ISSUE THREAD

**Issue by 000TragicSolitude** [ryyanmapes/minecart-mod#21]
On breaking a Minecart with Tank that's been placed in the world, it will drop an empty Minecart and a Chunk Loader block instead.
I don't exactly have a way to show any great example of this, but just ran into the issue now.

**Comment by ryyanmapes** [comment]
Oh whoops, that's a pretty big issue. I'm going to look into this.

**Comment by ryyanmapes** [comment]
Fixed in the new patch. Sorry about that, not sure how that slipped through testing.
