### ISSUE TITLE
Issues with Tank Loader/Unloader and its Redstone output methods

### ISSUE THREAD

**Issue by 000TragicSolitude** [ryyanmapes/minecart-mod#22]
When the Tank Loader interacts with its Minecart counterparts on Powered Locking Rails, they do not interact properly.
The Loader does not seem to perform correct math on the internal tank capacity, and counts ANY state (empty, partially filled, or filled) as "full".
To this extent, they will almost immediately allow the tank to pass through if on;
"Output redstone activation"
"Consider all Minecarts"
"Activate output when cart is full"
"Empty Loader slots entirely"

However, on;
"Output redstone activation"
"Consider only locked Minecarts"
"Activate output when cart is full"
"Empty Loader slots entirely"
The Loader will instead stutter with redstone pulses as the Loader is meeting its full condition (falsely), outputting a signal which unlocks the Lock rail, then turns the signal back off since the cart is no longer locked. It then repeats the process keeping the cart from going anywhere.

Further, on testing the Loader/Unloader when there is input/output inactivity on "Consider only locked minecarts," we get the same redstone continuous pulse issue.

One last additional issue is that the Unloader will just immediately unlock a rail if it has no ability to output anywhere. This can be seen in the video where my carts pass right past it despite it having fluid inside.

(The red wire band you've seen do not influence this behavior, as a fair heads-up. This is mainly meant to help show when this is happening as peeking under the carts every time can be an annoying way to check.)

Please see the video, [here](https://mega.nz/file/NNwFASQI#OqIw3LXx8yYPu1YzyUumchiDGuYp3ROb_d5x5HKEuv0), for a video displaying this issue.

**Comment by ryyanmapes** [comment]
Oh yikes, it looks like I really didn't test the tank and battery carts enough. Thank you for sending in this report, I'm going to look into this asap.

**Comment by ryyanmapes** [comment]
Alright, figured out the issue. I accidentally programmed it to output the fluid amount in the Loader/Unloader block, instead of the minecart. A fixed version should be out by tonight.

**Comment by Aivech** [comment]
> One last additional issue is that the Unloader will just immediately unlock a rail if it has no ability to output anywhere. This can be seen in the video where my carts pass right past it despite it having fluid inside.

This issue still occurs for me.
