### ISSUE TITLE
Chunkloader Cart Suggestions 

### ISSUE THREAD

**Issue by stargaze44** [ryyanmapes/minecart-mod#39]
Hi! I'm trying to use your mod in combination with Create (as I think many people do). 
Particularly, I'm trying to attach chunk loader minecarts to my train contraption to keep it loaded even when unmanned by a player. However, there's no easy way to do this because it seems like chunk loader minecarts are only active when powered by activator rails. 

Is there any chance you could add config options for the chunk loader minecart to enable it to be active all the time (or to be turned off by activator rails, as an inverse of its current behavior)?
I'm also trying to keep it loaded without needing to refill crystals; I can do that with the /data merge command in a repeating block, but a config option to make it require no fuel would be nice as well (as best I can tell, there _is_ a config option related to fuel but it seems to only be able to totally disable chunk loading or multiply its cost.

I totally understand if you don't feel this would be a balanced addition to the mod or if you just literally can't do it. It's simply something I would have liked to have in my usage of the mod, and I can imagine it would be something others would appreciate as well. Total sidenote that probably doesn't belong here, but I adore this mod and it's making railroad construction on my server less of a complete nightmare.
Thanks :)

**Comment by ryyanmapes** [comment]
The current behavior should allow it to stay running while not on an activator rail- I believe the activator rail acts as a toggle? As for the fuel thing, try making the fuel multiplier very large to make the cost negligible.
