### ISSUE TITLE
Chunkrodite returned from breaking a chunk loader doesn't factor in the chunk loader multiplier

### ISSUE THREAD

**Issue by kevin-wackman** [ryyanmapes/minecart-mod#40]
Hey there,

  I bumped up the `chunk_loader_multiplier` in the config of a single-player world since I would prefer if chunk loading is fairly cheap, and noticed that chunkrodite is effectively duplicated by the multiplier if you fuel and break the chunkloader
Reproduction steps:
 - Change the `chunk_loader_multiplier` to a higher value (100x is the most extreme example).
 - Power a chunk loader with some crystal
 - Break the chunk loader, receive the chunkrodite it drops
 - Power the chunk loader with the dropped chunkrodite
 - Break the chunk loader again, observe that much more chunkrodite drops

This isn't a huge problem (and honestly the blocks make cool decoration), but it is 100% reproducible.
As far as a fix, I would assume adding a quick div by the multiplier in [`dropExtras()` in ChunkLoaderTile.java](https://github.com/ryyanmapes/minecart-mod/blob/18f41a28404e60aace73a4eca9e4a041e6730781/src/main/java/com/alc/moreminecarts/tile_entities/ChunkLoaderTile.java#L281) should be enough to fix it, although I haven't tested it at all so take that with a grain of salt.

Let me know if you need any more information - I'm on 1.3.12, but it looks like this would happen across versions.

**Comment by ryyanmapes** [comment]
Oh geez, you're right, that is a pretty major oversight. I'll try to patch this as soon as I can.

**Comment by ryyanmapes** [comment]
This has been patched in the most recent version.
