### ISSUE TITLE
Minor gripe with some wording

### ISSUE THREAD

**Issue by Bluberry-Kat** [ryyanmapes/minecart-mod#41]
Hi! Forgive me for nitpicking;  
A recent update to Thermal Expansion added a new config option, "Standalone Redstone Flux", which optionally splits RF into a power system that is incompatible with Forge Energy. By default it's turned off, but  
Multiple of your devices (Minecart with Battery, Cart Loader, Cart Unloader) list their power capacity with the unit of RF, standing for "Redstone Flux", despite using the Forge Energy api.  
Previously, this was not an issue, but now that Redstone Flux and Forge Energy can be optionally split, this ambiguous use of energy units could potentially confuse players less familiar with the history of RF.  
I would personally modify the wording to say "FE" instead of "RF", but the specifics are of course your decision.

**Comment by ryyanmapes** [comment]
This is a good point, I will fix this in the next build.
