### ISSUE TITLE
Minecart with Tank not staying on Powered Locking Rail until empty

### ISSUE THREAD

**Issue by jamiedyoung6** [ryyanmapes/minecart-mod#44]
Using the unloader with a locking rail on top, if the tank cannot be emptied the entire way, a redstone pulse is emitted by the unloader. Unsure if this is intended or not.

**Comment by Bellwar** [comment]
This is big. I hate it. Any idea for a workaround? I have no idea how to read the minecart content to use redstone logic to somehow make it work.

**Comment by ryyanmapes** [comment]
I'm going to look into this. Is the desired behavior having the pulse only emit when the minecart is completely empty?

**Comment by Bellwar** [comment]
I think this is also on you how complex you want the menu to be. I feel like the behaviour: work is done (unloading is finished, but minecart has some amount inside) emit signal - has some use cases. 
On the other hand, if you transport fluid, energy or items just from A to B, if B gets filled up to the max, this behaviour right now starts to send the minecart between A and B non-stop. While I just want to make it stay on B until the minecart is empty and afterwards can get refilled on A. (Note: While writing, this might be also a thing with loader - haven't tested, I always had enough supply to fill the minecart)
I think this second scenario is much more used and also is the expectation (at least it was mine). So maybe add a button inside for changing between them? But how complex you want the unloader to be, that is your decision. 
I'm sorry for the long ramble.

**Comment by jamiedyoung6** [comment]
@Bellwar thanks for the great summary, it is exactly what I was thinking. My thoughts were that it should work like the items, i.e. the unloader doesn't emit a pulse until the cart is completely void of fluid.

**Comment by ryyanmapes** [comment]
Alright, I've fixed this issue on my end, and will be included in the next patch here in a few days.
