### ISSUE TITLE
Maglev and Lightspeed are equal speed?

### ISSUE THREAD

**Issue by paplaukes** [ryyanmapes/minecart-mod#48]
Hi,
this might be a request for information or a bug, I'm not sure.
I just found out after replacing a 1000+ length maglev line with lightspeed that the travel time stayed exactly the same, This on mostly straight line with a couple of turns. Way I built was 2 powered rails + 32 normal ones. I've since tested both types of rails side to side on a 120 length straight line and times stay equal whether I do 2+32 or 3+32 . So... how does one reach the extremely high max speed mentioned in readme?

Playing on Create: Above and Beyond modpack v. 1.3 with More Minecarts v. 1.3.12

**Comment by ryyanmapes** [comment]
Are you using powered maglev rails? I've gotten a similar bug report, so it's possible there's something up with Maglev rails. On my end they are definitely much faster, but perhaps the properties are being overridden somehow?

**Comment by paplaukes** [comment]
I was using 2 powered maglev rails followed by 32 maglev rails. Changed to 2 powered lightspeed rails followed by 32 lightspeed rails. Same travel times.

**Comment by paplaukes** [comment]
I've tested on a fresh MC 1.6.5 + Forge 36.2.20 + More Minecarts 1.3.12 instance now. Maglev and Lightspeed perform at the same speed. Perhaps I'm placing too little powered rails? I've read 1 powered +32 rails is ok for vanilla, I've been using twice to triple that.

**Comment by ryyanmapes** [comment]
Have you tried using aerodynamic minecarts? It's possible that it's ending up the same speed because higher velocity = higher drag in normal minecarts

**Comment by paplaukes** [comment]
I've tried those and ended up assuming they're meant for automated non player travel, because I'm not able to board them. If I'm in an aerodynamic minecart and try moving onto a powered rail, I just walk through the minecart without it moving. If I'm in the minecart and press a button to power a powered rail under me the cart gets launched and I stay in place.

A suggestion, if aerodynamic minecarts are meant to be used by players it'd be really nice to just get a permanent version of the cart, as right now it drops as 2 items and has to be reassembled for each travel.

**Comment by paplaukes** [comment]
I managed to make the aerodynamic cart work. When I apply an upgrade it moves me directly into the minecart position. My mistake was assuming I was sitting when I get moved, but I wasn't. I had to do one more right click.

When testing with aerodynamic cart, whether in modded world or the clean one, I get equal speeds on both types of tracks. It is about 10% slower than vanilla minecart, which also gets equal speeds on both maglev and lightspeed rails.

**Comment by ryyanmapes** [comment]
That's really weird. I'm going to look into this- it's possible a forge update broke something.

**Comment by ryyanmapes** [comment]
This will be fixed in the next patch which will be released soon.

**Comment by ryyanmapes** [comment]
(it will still require using Aerodynamic minecarts however)

**Comment by paplaukes** [comment]
Thank you! Will be enjoying maglev speeds and other rails meanwhile. Been doing signal rails for metro stops & found a use for crossovers/turns too.

**Comment by ryyanmapes** [comment]
Awesome, I'm glad you're enjoying it!
