### ISSUE TITLE
[Question] Do you have plans on 1.18 port?

### ISSUE THREAD

**Issue by KKotik** [ryyanmapes/minecart-mod#49]
The mod really going well with create. I wonder, do you have plans on 1.18 port in the future?

Thank you.

**Comment by Nick-McKay** [comment]
Same question

**Comment by ryyanmapes** [comment]
I'm not sure. Not any time soon, tbh, but maybe later in the spring?

**Comment by KKotik** [comment]
Thank you for answer! Really excited for that.

**Comment by ryyanmapes** [comment]
(Porting wasn't as bad as I'd expected, and the new version is actually out now!)
