### ISSUE TITLE
Unloader not working as expected 

### ISSUE THREAD

**Issue by IamStig** [ryyanmapes/minecart-mod#53]
Mod version 1.3.12 (1.16.5) 
Mod Pack Create Above & Beyond
I have the minecart and tank working fine with the loader but the unloader is not behaving as expected. I am using locking rails and the loader fills a cart then sends it as expected but when it arrives the locking rail appears to be getting a signal before the cart arrives and 575mb of fluid is remove without the cart actually stopping. It instead travels back the the loader and returns but this time it stops and unloads. I am only testing this over a 9-10 block line so the double journey doesn't seem a big problem but if I was using it as I intend over a 800-1000 block line it would be....also not certain the stopping after doing the trip twice would still be happening. Any ideas why this is occurring?

**Comment by ryyanmapes** [comment]
This has been fixed in the mod version 1.3.14. It will be fixed automatically when Create Above and Beyond updates it's version.
