### ISSUE TITLE
Lack of config options

### ISSUE THREAD

**Issue by Auuki** [ryyanmapes/minecart-mod#54]
Config file does not allow for adjustment of generation stuff (like cactuses). Some people might want to adjust generation or completely disable it like in my case. I can disable recipes using CraftTweaker but world gen needs a config option. It would also be great if we could adjust maximum speeds on different rail types.

Based on 1.18.1 version.

**Comment by ryyanmapes** [comment]
I'm going to look into this.

**Comment by ryyanmapes** [comment]
This has been fixed in the new versions.
