### ISSUE TITLE
Chunk Loaders do not work.

### ISSUE THREAD

**Issue by indecisiveCuriosity** [ryyanmapes/minecart-mod#59]
Chunk Loaders and Chunk Loader Carts do not work in the 1.18.1 version. On Forge 39.0.

**Comment by ryyanmapes** [comment]
They seemed to work fine when I tested them. What dimension are you using them in, and how do you know something is going wrong?

**Comment by indecisiveCuriosity** [comment]
I attempted to use them in the overworld, and had two tests. The first was a minecart track going outside of player chunk loading range with a loop at the end. The second was placing a chunk loader by a furnace and exiting player chunk loading range, then returning after a few minutes. I attempted it with other mods loaded as well as standalone, only having More Minecarts and Rails.

**Comment by ryyanmapes** [comment]
Just to make sure, they were powered on and fueled?

**Comment by indecisiveCuriosity** [comment]
Yes. I made sure they were fueled and tested both powered on and unpowered in the case I was mistaking which state was which.

**Comment by ryyanmapes** [comment]
Are you playing on a server? I'm going to look into this.

**Comment by ryyanmapes** [comment]
Alright, I've fixed this issue on my end, and the fix will be up within the next 24 hours.
Side note, to whom it may concern: 'registerTickingTicket' and 'addRegionTicket' are swapped and misnamed currently in the 1.18.1 Forge codebase. Until this is fixed, modders will have to feed the opposite boolean value into the 'ticking' parameter than they would expect.
