### ISSUE TITLE
Stasis chambers causing rendering issue

### ISSUE THREAD

**Issue by Niall-mc** [ryyanmapes/minecart-mod#62]
Version: 1.3.15, 1.16.5, latest forge

Stasis chambers are causing issues such as red power cables and cc: tweaked monitors to not render at all or incorrectly. 

[latest.log](https://github.com/ryyanmapes/minecart-mod/files/8564971/latest.log)
[CC-Tweaked issue](https://github.com/cc-tweaked/CC-Tweaked/issues/1077)

**Comment by ryyanmapes** [comment]
This has been fixed in the most recent patch release.

**Comment by MattB70** [comment]
This also occurs on 1.18.2 with the same conditions.

**Comment by ryyanmapes** [comment]
Just fixed in new release.
