### ISSUE TITLE
[Feature Request] Speed Rails

### ISSUE THREAD

**Issue by Tumbllekush** [ryyanmapes/minecart-mod#7]
Hello, I'm very new to Github, so I don't know where to specifically ask for requests. Also, I don't know if you're taking requests either; you're free to deny it. However, please know your mod is the only rails mod updated to 1.16, so I greatly appreciate your work!
The request I have in detail is just for speed rails. It could be done like the BetterRails mod, in that there is a greater variant of Powered Rails that uses iron. Alternatively, there could be another minecart variant that has a higher speed cap than a normal cart.
Again, I apologize if you are not taking requests, or you have discontinued the mod regarding features. I'm sorry if this isn't the place for requests, either.

**Comment by ryyanmapes** [comment]
No problem, you're in the right place! I'm going to look into making high speed rails and carts. Still debating high-speed pushcarts.
