### ISSUE TITLE
Loading furnace minecart with fuel causes integer overflow in fuel counter

### ISSUE THREAD

**Issue by PORTB** [ryyanmapes/minecart-mod#79]
Having a furnace minecart on some sort of loop that has a minecart loader filled with fuel will eventually make the minecart's fuel counter overflow and become negative. While this normally will 'fix' itself when the counter underflows again, it causes issues with create contraptions. 
This is what I used to trigger the bug
![image](https://user-images.githubusercontent.com/34615701/193413901-74e2cf75-568f-4876-bd2c-68c275d778d3.png)

The fuel counter overflowed after the minecart was reloaded. The fuel level has to be low enough to refuel but high enough to overflow so it took a few minutes. I used the /data command to show the fuel level of the minecart

Version: moreminecarts-1.5.3

**Comment by ryyanmapes** [comment]
Wow, an overflow bug in the wild? I'll look into this!

**Comment by PORTB** [comment]
Change

```java
if (minecart.fuel + 3600 <= 32000) {

    for (ItemStack stack : items) {
        if (Ingredient.of(new ItemLike[]{Items.COAL, Items.CHARCOAL}).test(stack) && !(leave_one_in_stack && stack.getCount() == 1)) {
            stack.shrink(1);
            minecart.fuel += 3600;
            changed = true;

        }
    }
}
```

to something like

````java
for(int stackIndex = 0; (minecart.fuel + 3600 <= 32000) && (stackIndex < items.size()); stackIndex++)
{
    ItemStack stack = items.get(stackIndex);

    if (Ingredient.of(new ItemLike[]{Items.COAL, Items.CHARCOAL}).test(stack) && !(leave_one_in_stack && stack.getCount() == 1)) {
        stack.shrink(1);
        minecart.fuel += 3600;
        changed = true;
    }
}
```

And similar for the locking rail loop above it. I didn't see your reply until just now

**Comment by ryyanmapes** [comment]
Sorry for the long response time. This has been fixed and included in the new version. Thank you so much for your help!
