### ISSUE TITLE
Later Versions?

### ISSUE THREAD

**Issue by Antommino** [ryyanmapes/minecart-mod#8]
Hello!! I was wondering if you could maybe add the mod to later version of minecraft? Maybe like 1..16.4, 1.12.2, etc.
Thanks in advance!!

**Comment by ianlavr** [comment]
1.12.2 isnt a later version. Use Railcraft for 1.12.2. 1.16.4 is compatible with 1.16.5

**Comment by Nick-McKay** [comment]
Are you planning to update to 1.18.1?

**Comment by ryyanmapes** [comment]
Maybe, haven't decided.
