### ISSUE TITLE
[Feature Request] Variants of Campfire Cart From The Endergetic Expansion and Infernal Expansion

### ISSUE THREAD

**Issue by SalehGrey** [ryyanmapes/minecart-mod#9]
https://www.curseforge.com/minecraft/mc-mods/infernal-expansion
https://www.curseforge.com/minecraft/mc-mods/endergetic

Both mods add a new campfire. I don't know if it's worth it to add integration, but considering how popular Abnormals Core mods are I don't think it could hurt. It's up to you, though.

**Comment by ryyanmapes** [comment]
I'm going to look into this for a future update.

**Comment by ryyanmapes** [comment]
Ender campfire cart has been added. Another nether campfire cart felt redundant.
