### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mike23564** [ryyanmapes/minecart-mod#93]
I know this'll be a pain reading this suggestion but could there be a 1.20.1 version of the mod? Not asking for it to be any time soon in the slightest, just for it to exist some time down the line, I make this suggestion as a lot of other mods I'm planning to have are either currently on 1.20.1 and have slow development or they have stopped development ending on 1.20.1, and I'm sure a lot of other people with modded worlds have experienced the same, been watching this mod for it's update but just noticed it skipped to .2, which isn't a problem as I've heard 1.20.1 has been a pain for many modding teams, but without any like, discord or anything to see a roadmap or even just ask general inquries or see if 1.20.1 is already planned, I thought I might as well just leave this as a suggestion, I appreciate all you've done with this mod and I hope this suggestion isn't too much of an annoyance to hear out, and like I said, I'm not trying to be like "right now right now right now", just leaving a suggestion in the hopes it'll happen sometime in the future, keep up the good work.
(also idk if I was to leave this under issues or pull requests but I saw a majority of suggestions being put under issues so I just did the same)

**Comment by ryyanmapes** [comment]
Should be up now!
