### ISSUE TITLE
Port for 1.20.1

### ISSUE THREAD

**Issue by traincrisis** [ryyanmapes/minecart-mod#94]
Can you please port this to 1.20.1? Just many mods are for this version but there aren't very much of mods for 1.20.2 so please port it to 1.20.1

**Comment by mike23564** [comment]
I made this suggestion as well lol, like i don't care when it gets here, just as long as it does some time down the line, fact is that sop many mod teams get burnt out with making a 1.20.1 port that they slow down for a while, and not only that but a lot of mod teams only update to popular versions, the main ones across history that I've noticed are 1.7, 1.8, 1.12.2, 1.16, 1.18, and 1.20.1, majority of mods in the 1.20s are in .1 and not .2

**Comment by ryyanmapes** [comment]
Currently testing a build of a 1.20.1 version, will be up soon.

**Comment by mike23564** [comment]
Thank you so much

**Comment by mike23564** [comment]
@ryyanmapes thank you so much
